### ISSUE TITLE
Networks don't work with Joyent Triton Docker API implementation

### ISSUE THREAD

**Issue by alaslums** [terraform-providers/terraform-provider-docker#63]
Hi There,

It looks like this provider performs a two-step process when you specify a network, and creates the docker container, then attaches a network to it.

Unfortunately the Triton Docker API doesn't currently support connecting networks after container creation, which means this:

```
resource "docker_container" "database" {
  name    = "database"
  image   = "${docker_image.percona.latest}"
  networks = ["internal-2720"]
}
```
Fails with:
```
* docker_container.database: Unable to connect to network 'internal-2720': API error (400): (NotImplemented) network connect is not implemented (5349d3cd-33 f1-45fd-8cdc-a37a06768a71)
```

"docker run --network=", or docker-compose both work fine, as these pass the network configuration in via the Docker create API call.

It should hopefully be a simple enough fix to pass the network config in via the create command instead.

**Comment by mavogel** [comment]
This is probably related to #92 and all its referenced issues in there. Will be tackled together with those issues in the next minor release

**Comment by mavogel** [comment]
@alaslums could you make me favor and re-test if this bug still occurs for the Triton API
IMHO with the changes after you filed the bug
- migration to the official docker client in https://github.com/terraform-providers/terraform-provider-docker/pull/70
- various network fixed in https://github.com/terraform-providers/terraform-provider-docker/pull/92

If it does not work with the latest `1.0.4` release then feel free to build the latest from `master` locally
```sh
$ go build -o terraform-provider-docker_v1.1.0 
$ mv -f terraform-provider-docker_v1.1.0 ~/.terraform.d/plugins/$(go env GOOS)_$(go env GOARCH)
```

```hcl
provider "docker" {
  version = "1.1.0"
  host    = "unix:///var/run/docker.sock"
}

resource "docker_container" "database" {
  name    = "database"
  image   = "${docker_image.percona.latest}"
  networks = ["internal-2720"]
}
```

**Comment by mavogel** [comment]
I will close it due to unresponsiveness. Feel free to re-open if the problem still exists :)
